name: transcendence

include:
  - ./gateway/docker-compose${SSL_PROVIDED:+.ssl}.yaml
  - ./database/docker-compose.yaml
  - ./backend/docker-compose.yaml
  - ./frontend/docker-compose${FRONTEND_MODE:+-${FRONTEND_MODE}}.yaml
  - ./pki/docker-compose.yaml
  - ./monitoring/docker-compose.yaml

volumes:
  certs_data:
  db_data:
  prometheus_data:
  grafana_data:
