server {
    root /usr/share/nginx/html;
    index index.html;

    listen 443 ssl;
    listen [::]:443 ssl;
    server_name frontend;

    ssl_certificate /certs/${INT_CRT_NAME};
    ssl_certificate_key /certs/${INT_KEY_NAME};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name frontend;
    return 301 https://$host$request_uri;
}

#MONITORING
server {
    listen 8443 ssl;
    server_name frontend-internal;

    ssl_certificate     /certs/${INT_CRT_NAME};
    ssl_certificate_key /certs/${INT_KEY_NAME};
    ssl_protocols       TLSv1.2 TLSv1.3;

    location = /stub_status {
        stub_status;
        access_log off;
    }

    location / {
        return 404;
    }
}