services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - CA_CRT_NAME=${CA_CRT_NAME:-ca.crt}
      - INT_CRT_NAME=${INT_CRT_NAME:-internal.crt}
      - INT_KEY_NAME=${INT_KEY_NAME:-internal.key}
      - ENVSUBST_VARS=CA_CRT_NAME,INT_CRT_NAME,INT_KEY_NAME
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template:ro
      - certs_data:/certs:ro
    restart: always
    depends_on:
      pki-init:
        condition: service_completed_successfully
