# Redirect HTTP to HTTPS
server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    # SSL files from environment variables
    ssl_certificate     ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;

    # Set up resolver for service discovery
    resolver 127.0.0.11 valid=30s;

    # Shared proxy settings
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # Route to Frontend Service
    location / {
        set $frontend_service "http://frontend:80";
        proxy_pass $frontend_service;
    }

    # Route to Core Backend Service
    location /api/ {
        set $backend_service "http://backend:8000";
        proxy_pass $backend_service;
    }
}
