services:
  gateway:
    build:
      context: .
      args:
        - SSL_CERT=${SSL_CERT}
        - SSL_KEY=${SSL_KEY}
    container_name: gateway
    environment:
      - NGINX_ENVSUBST_FILTER=SSL_CERT|SSL_KEY
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/templates/default.conf.template:ro
      - ../../${SSL_DIR}:/${SSL_DIR}:rw
    restart: always
