services:
  prometheus:
    image: prom/prometheus:v3
    container_name: prometheus
    environment:
      - CA_CRT_NAME=${CA_CRT_NAME:-ca.crt}
      - INT_CRT_NAME=${INT_CRT_NAME:-internal.crt}
      - INT_KEY_NAME=${INT_KEY_NAME:-internal.key}
      - TMPL=/etc/prometheus/templates
      - CONF=/tmp
    entrypoint: []
    command: >
      sh -xc "
      cat $$TMPL/prometheus.yml.template &&
      cat $$TMPL/web-config.yml.template &&
      sed 
      -e 's|__CA_CRT_NAME__|'$$CA_CRT_NAME'|g'
      -e 's|__INT_CRT_NAME__|'$$INT_CRT_NAME'|g'
      -e 's|__INT_KEY_NAME__|'$$INT_KEY_NAME'|g'
      $$TMPL/prometheus.yml.template > $$CONF/prometheus.yml &&
      sed 
      -e 's|__INT_CRT_NAME__|'$$INT_CRT_NAME'|g'
      -e 's|__INT_KEY_NAME__|'$$INT_KEY_NAME'|g'
      $$TMPL/web-config.yml.template > $$CONF/web-config.yml &&
      cat $$CONF/prometheus.yml &&
      cat $$CONF/web-config.yml &&
      exec 
      /bin/prometheus
      --config.file=$$CONF/prometheus.yml
      --web.config.file=$$CONF/web-config.yml
      --storage.tsdb.path=/prometheus
      "
    volumes:
      - ./prometheus/prometheus.yml.template:/etc/prometheus/templates/prometheus.yml.template:ro
      - ./prometheus/web-config.yml.template:/etc/prometheus/templates/web-config.yml.template:ro
      - certs_data:/certs:ro
      - prometheus_data:/prometheus
    restart: always
    depends_on:
      pki-init:
        condition: service_completed_successfully
