services:

  database:
    image: mysql:8.4
    env_file:
      - ../../.env
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout:  5s
      retries:  5
      start_period: 30s
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - certs_data:/certs:ro
    environment:
      MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:       ${DB_NAME}
      MYSQL_USER:           ${DB_USER}
      MYSQL_PASSWORD:       ${DB_PASSWORD}
    command:
      - mysqld
      - --ssl-ca=/certs/${CA_CRT_NAME:-ca.crt}
      - --ssl-cert=/certs/${INT_CRT_NAME:-internal.crt}
      - --ssl-key=/certs/${INT_KEY_NAME:-internal.key}

  data-service:
    build: ./data-service
    env_file:
      - ../../.env
    container_name: ${SERVICE_CONTAINER_NAME}
    restart: unless-stopped
    expose:
      - "9000"
    # ports:
    #   - "9000:9000"
    depends_on:
      pki-init:
        condition: service_completed_successfully
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      INT_CRT_NAME: ${INT_CRT_NAME:-internal.crt}
      INT_KEY_NAME: ${INT_KEY_NAME:-internal.key}
    volumes:
      - certs_data:/certs:ro
    command: >
      sh -c "
      uvicorn main:app
      --host 0.0.0.0
      --port 9000
      --ssl-certfile=/certs/$${INT_CRT_NAME}
      --ssl-keyfile=/certs/$${INT_KEY_NAME}
      "
