apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    isDefault: true
    jsonData:
      tlsSkipVerify: false
      serverName: prometheus
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: "$__file{/tmp/ca.crt}"