"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta  #this allow us to set the lifetime of the JWT tokens in settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'transcendence.42.fr',
    'localhost',
    '127.0.0.1',
    ]

# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARD_PROTO', 'https')

# SECURE_SSL_DIRECT = True

# SESSION_COOKIE_SECURE = True  # requires https

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Enable JWT authentication globally for the API, both for authentication and permissions.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# update the JWT settings and added temp comments to explain the each setting (for eventual later adjustment)
SIMPLE_JWT = {
        # how long the jwt token is valid
        'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
        # how long the refresh token is valid
        'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
        # when the client refreshes (refresh token rotation) issue a NEW refresh token and invalidate the old one
        'ROTATE_REFRESH_TOKENS': True,
        # after rotation, add the old refresh token to the blacklist table in the DB (Django DB)
        'BLACKLIST_AFTER_ROTATION': True,
        # the signing token algorithm. HS256 = HMAC with SHA-256 (symmetric)
        'ALGORITHM': 'HS256',
        # uses Django secret key by default, but we can set a separate JWT key later if necessary
        # 'SIGNING_KEY': os.getenv('JWT_SECRET_KEY'),
        # prefix in the Authorization header: "Authorization: Bearer <token>"
        'AUTH_HEADER_TYPES': ('Bearer',),
        # fields in the token payload that identify the user (default is 'user_id' but we can change it if needed)
        'USER_ID_FIELD': 'id',
        'USER_ID_CLAIM': 'user_id',
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email'),
            'max_similarity': 0.7,
            }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_lenght': 10,
            }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CORS — which frontend origins are allowed to make requests
# In development, our Vite dev server runs here:
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",    
    "https://localhost:5173",  
    "https://transcendence.42.fr",
]

# Allows the browser to send cookies (the httpOnly refresh token cookie)
# cross-origin. Without this, credentials: "include" in the frontend fetch calls will fail silently.
CORS_ALLOW_CREDENTIALS = True
# ! IMPORTANT !: Ask frontend to include credentials: "include" in fetch calls that need to send cookies (refresh token cookie) or receive cookies (logout endpoint that clears the cookie)

# Allow the Authorization header so the browser doesn't strip it
CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'x-csrftoken',
]

# Internal data-service proxy info config (from .env.example)
DATA_SERVICE_URL = os.getenv("DATA_SERVICE_URL", "https://data-service:9000/api")
DATA_SERVICE_TOKEN = os.getenv("DATA_SERVICE_TOKEN", "dev-internal-token")
DATA_SERVICE = os.getenv("DATA_SERVICE", "http://data-service:9000/api")

# Authentication / OAuth2 config
FORTYTWO_CLIENT_ID     = os.getenv("FORTYTWO_CLIENT_ID")
FORTYTWO_CLIENT_SECRET = os.getenv("FORTYTWO_CLIENT_SECRET")
FORTYTWO_REDIRECT_URI  = os.getenv("FORTYTWO_REDIRECT_URI")
JWT_ACCESS_LIFETIME_MINUTES = os.getenv("JWT_ACCESS_LIFETIME_MINUTES", 30)
JWT_REFRESH_LIFETIME_DAYS = os.getenv("JWT_REFRESH_LIFETIME_DAYS", 7)
OAUTH_SUCCESS_REDIRECT = os.getenv("OAUTH_SUCCESS_REDIRECT", "https://127.0.0.1/login/success")
OAUTH_FAILURE_REDIRECT = os.getenv("OAUTH_FAILURE_REDIRECT", "https://127.0.0.1/login/error")
