{
 "title": "Django",
 "description": "Backend dashboard using django-prometheus metrics exporter",
 "tags": [
  "Web",
  "Django",
  "Database",
  "Cache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "application", "label": "application", "query": { "query": "label_values(python_info,app)" } },
   {
    "name": "threshold",
    "label": "threshold",
    "query": "100ms : 0.1, 250ms : 0.25, 500ms : 0.5, 750ms : 0.75, 1s : 1.0, 2.5s : 2.5, 5s : 5.0, 7.5s : 7.5, 10s : 10.0, 25s : 25.0"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_before_middlewares_total{job=\"backend\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{job=\"backend\"})"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes{job=\"backend\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Uncollectable",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(python_gc_objects_uncollectable_total{job=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming Responses",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(django_http_responses_streaming_total{job=\"backend\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"backend\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "GC Collections/s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(python_gc_collections_total{job=\"backend\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Number of Requests by Processing Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_including_middlewares_seconds_bucket{job=\"backend\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Number of Responses by Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_body_total_bytes_bucket{job=\"backend\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_including_middlewares_seconds_bucket{job=\"backend\"}[$__rate_interval])) by (le))",
     "legendFormat": "50 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_including_middlewares_seconds_bucket{job=\"backend\"}[$__rate_interval])) by (le))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(django_http_requests_latency_including_middlewares_seconds_bucket{job=\"backend\"}[$__rate_interval])) by (le))",
     "legendFormat": "99 quantile"
    }
   ]
  },
  {
   "title": "GC Collections by Generation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(python_gc_collections_total{job=\"backend\"}[$__rate_interval])) by (generation)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Slower Than $threshold",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "1 - (sum(max_over_time(django_http_requests_latency_including_middlewares_seconds_bucket{job=\"backend\",le=\"$threshold\"}[$__range])) / sum(max_over_time(django_http_requests_latency_including_middlewares_seconds_count{job=\"backend\"}[$__range])))",
     "legendFormat": "slower-than-threshold"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{job=\"backend\"}[$__rate_interval]))",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"backend\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "GC Objects Collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(irate(python_gc_objects_collected_total{job=\"backend\"}[$__rate_interval])) by (generation)",
     "legendFormat": "generation {{generation}}"
    }
   ]
  }
 ]
}